ReadMe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('history/', include('history.urls')),
    path('list-book/', include('listBook.urls')),
    path('book-details/', include('bookDetails.urls')),
    path('diskusi-book/', include('diskusiBook.urls')),
    path('rating-book/', include('ratingBook.urls')),
    path('wishlist-book/', include('wishlistBook.urls')),
]

diskusiBook/urls.py
from django.urls import path
from main.views import show_main
from diskusiBook.views import show_discussion, show_post, create_post, get_post_json, remove_post, edit_post, show_json, create_post_flutter, edit_post_flutter, remove_post_flutter, get_username, get_comment_json, get_reply_json, create_comment, edit_comment, remove_comment, get_single_post_json, create_reply, edit_reply, remove_reply, show_json_comment, show_json_reply, create_comment_flutter, edit_comment_flutter, remove_comment_flutter, create_reply_flutter, edit_reply_flutter, remove_reply_flutter

app_name = 'diskusiBook'

urlpatterns = [
    path('diskusi-book/<int:id>/', show_discussion, name='show_discussion'),
    path('show_post/<int:id>/', show_post, name='show_post'),
    path('create_post/<int:id>/', create_post, name='create_post'),
    path('get_post/<int:id>/', get_post_json, name='get_post_json'),
    path('get_single_post_json/<int:id>/', get_single_post_json, name='get_single_post_json'),
    path('get_comment/<int:id>/', get_comment_json, name='get_comment_json'),
    path('get_reply/<int:id>/', get_reply_json, name='get_reply_json'),
    path('remove_post/<int:id>/', remove_post, name='remove_post'),
    path('edit_post/<int:id>/', edit_post, name='edit_post'),
    path('create_comment/<int:id>/', create_comment, name='create_comment'),
    path('create_comment_flutter/', create_comment_flutter, name='create_comment_flutter'),
    path('remove_comment/<int:id>/', remove_comment, name='remove_comment'),
    path('remove_comment_flutter/', remove_comment_flutter, name='remove_comment_flutter'),
    path('edit_comment/<int:id>/', edit_comment, name='edit_comment'),
    path('edit_comment_flutter/', edit_comment_flutter, name='edit_comment_flutter'),
    path('create_reply/<int:id>/', create_reply, name='create_reply'),
    path('create_reply_flutter/', create_reply_flutter, name='create_reply_flutter'),
    path('remove_reply/<int:id>/', remove_reply, name='remove_reply'),
    path('remove_reply_flutter/', remove_reply_flutter, name='remove_reply_flutter'),
    path('edit_reply/<int:id>/', edit_reply, name='edit_reply'),
    path('edit_reply_flutter/', edit_reply_flutter, name='edit_reply_flutter'),
    path('json/', show_json, name='show_json'),
    path('json-comment/', show_json_comment, name='show_json_comment'),
    path('json-reply/', show_json_reply, name='show_json_reply'),
    path('create_post_flutter/', create_post_flutter, name='create_post_flutter'),
    path('edit_post_flutter/', edit_post_flutter, name='edit_post_flutter'),
    path('remove_post_flutter/', remove_post_flutter, name='remove_post_flutter'),
    path('get_username/<int:user_id>/', get_username, name='get_username'),
]

main/urls.py
from django.urls import path
from . import views # Tambah ini
from main.views import search_books, show_main, database_make, register, login_user, logout_user
from main.views import get_book, add_book

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('SECRET-ONLY/', database_make, name='database_make'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add_book/', add_book, name='add_book'),
    path('get-book/', get_book, name='get_book'),
    path('search-books/', search_books, name='search_books'),
]

diskusiBook/models.py
from django.db import models
from django.urls import reverse
from main.models import Book
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.shortcuts import reverse

# Create your models here.
    
class Post(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    
class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

diskusiBook/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content"]

diskusiBook/views.py
from django.http import Http404, HttpResponse, HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from main.views import Book
from .models import Comment, Post, Reply
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
import json

def get_post_json(request, id):
    book = get_object_or_404(Book, id=id)
    posts = Post.objects.filter(book=book)
    return HttpResponse(serializers.serialize('json', posts))

def get_comment_json(request, id):
    post = get_object_or_404(Post, id=id)
    comments = Comment.objects.filter(post=post)
    return HttpResponse(serializers.serialize('json', comments))

def get_reply_json(request, id):
    comment = get_object_or_404(Comment, id=id)
    replies = Reply.objects.filter(comment=comment)
    return HttpResponse(serializers.serialize('json', replies))

def get_single_post_json(request, id):
    post = Post.objects.filter(id=id)
    return HttpResponse(serializers.serialize('json', post))

def show_discussion(request, id): 
    book = get_object_or_404(Book, id=id)
    posts = Post.objects.filter(book=book)

    context = {
        'posts': posts,
        'book': book,
        'name': request.user.username,
        'user_id': request.user.id
    }

    return render(request, "thread.html", context)

@login_required(login_url='main:login')
@csrf_exempt
def show_post(request, id):
    post = get_object_or_404(Post, pk=id)
    book = get_object_or_404(Book, id=post.book.pk)
    comments = Comment.objects.filter(post=post)
        
    context = {
        'post': post,
        'book': book,
        'comments': comments,
        'name': request.user.username,
    }
    return render(request, 'post.html', context)


def show_json(request):
    data = Post.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_comment(request):
    data = Comment.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_reply(request):
    data = Reply.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def get_username(request, user_id):
  try:
    user = User.objects.get(pk=user_id)
    return JsonResponse({'username': user.username})
  except User.DoesNotExist:
    raise Http404("User does not exist")

@login_required(login_url='main:login')
@csrf_exempt
def create_post(request, id):
    form = PostForm(request.POST or None)
    book = get_object_or_404(Book, id=id)

    if form.is_valid() and request.method == "POST":
        post = form.save(commit=False)
        post.user = request.user
        post.book = book
        post.save()
        return HttpResponseRedirect(reverse('diskusiBook:show_discussion', args=[id]))
    
    context = {'form': form, 'book': book}
    return render(request, "create_post.html", context)

@csrf_exempt
def create_post_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_post = Post.objects.create(
            user = request.user,
            title = data["title"],
            content = data["content"],
            book = get_object_or_404(Book, id=data["book"]),
        )

        new_post.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@login_required(login_url='main:login')
@csrf_exempt
def remove_post(request, id):
    if request.method == "GET":
        post = get_object_or_404(Post, pk=id, user=request.user)
        post.delete()
        return HttpResponse(b"DELETED", status=201)
    return HttpResponseNotFound()

@login_required(login_url='main:login')
@csrf_exempt
def remove_post_flutter(request):
    if request.method == "POST":
        data = json.loads(request.body)
        post = get_object_or_404(Post, pk=data["post"], user=request.user)
        post.delete()
        return JsonResponse({"status": "success", "message": "Post telah berhasil dihapus."}, status=201)
    return JsonResponse({"status": "error", "message": "Terdapat kesalahan. Silahkan coba lagi."}, status=404)

@login_required(login_url='main:login')
@csrf_exempt
def edit_post(request, id):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=id, user=request.user)
        post.title = request.POST.get("title")
        post.content = request.POST.get("content")
        post.save()
        return HttpResponse(b"EDITED", status=201)
    return HttpResponseNotFound()

@login_required(login_url='main:login')
@csrf_exempt
def edit_post_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        post = get_object_or_404(Post, pk=data["post"], user=request.user)
        post.title = data["title"]
        post.content = data["content"]

        post.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
@login_required(login_url='main:login')
@csrf_exempt
def create_comment(request, id):
    if request.method == "POST":
        commentcontent = f'Commentcontent{id}'
        comment_text = request.POST.get(commentcontent)
        post = get_object_or_404(Post, pk=id)

        comment = Comment.objects.create(
            post=post,
            user=request.user, 
            content=comment_text,
        )

        comment.save()
    
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def create_comment_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_comment = Comment.objects.create(
            user = request.user,
            content = data["content"],
            post = get_object_or_404(Post, id=data["post"]),
        )

        new_comment.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@login_required(login_url='main:login')
@csrf_exempt
def remove_comment(request, id):
    if request.method == "GET":
        comment = get_object_or_404(Comment, pk=id, user=request.user)
        comment.delete()
        return HttpResponse(b"DELETED", status=201)
    return HttpResponseNotFound()

@login_required(login_url='main:login')
@csrf_exempt
def remove_comment_flutter(request):
    if request.method == "POST":
        data = json.loads(request.body)
        comment = get_object_or_404(Comment, pk=data["comment"], user=request.user)
        comment.delete()
        return JsonResponse({"status": "success", "message": "Comment telah berhasil dihapus."}, status=201)
    return JsonResponse({"status": "error", "message": "Terdapat kesalahan. Silahkan coba lagi."}, status=404)

@login_required(login_url='main:login')
@csrf_exempt
def edit_comment(request, id):
    if request.method == "POST":
        comment = get_object_or_404(Comment, pk=id, user=request.user)
        commenteditcontent = f'CommentEditcontent{id}'
        comment.content = request.POST.get(commenteditcontent)
        comment.save()
        return HttpResponse(b"EDITED", status=201)
    return HttpResponseNotFound()

@login_required(login_url='main:login')
@csrf_exempt
def edit_comment_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        comment = get_object_or_404(Comment, pk=data["comment"], user=request.user)
        comment.content = data["content"]

        comment.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@login_required(login_url='main:login')
@csrf_exempt
def create_reply(request, id):
    if request.method == "POST":
        replycontent = f'Replycontent{id}'
        reply_text = request.POST.get(replycontent)
        comment = get_object_or_404(Comment, pk=id)

        reply = Reply.objects.create(
            comment=comment,
            user=request.user, 
            content=reply_text,
        )

        reply.save()
    
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def create_reply_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_reply = Reply.objects.create(
            user = request.user,
            content = data["content"],
            comment = get_object_or_404(Comment, id=data["comment"]),
        )

        new_reply.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@login_required(login_url='main:login')
@csrf_exempt
def remove_reply(request, id):
    if request.method == "GET":
        reply = get_object_or_404(Reply, pk=id, user=request.user)
        reply.delete()
        return HttpResponse(b"DELETED", status=201)
    return HttpResponseNotFound()

@login_required(login_url='main:login')
@csrf_exempt
def remove_reply_flutter(request):
    if request.method == "POST":
        data = json.loads(request.body)
        reply = get_object_or_404(Reply, pk=data["reply"], user=request.user)
        reply.delete()
        return JsonResponse({"status": "success", "message": "Reply telah berhasil dihapus."}, status=201)
    return JsonResponse({"status": "error", "message": "Terdapat kesalahan. Silahkan coba lagi."}, status=404)

@login_required(login_url='main:login')
@csrf_exempt
def edit_reply(request, id):
    if request.method == "POST":
        reply = get_object_or_404(Reply, pk=id, user=request.user)
        replyeditcontent = f'ReplyEditcontent{id}'

diskusiBook/templates/create_post.html
{% include 'header.html' %}

{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block meta %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock meta %}
    <title>Discussion Thread</title>
    <link rel="stylesheet" href="{% static 'css/create_post.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
</head>

<body>
    <main>
        <h1>Create New Post</h1>

        <form method="POST" id="post-form">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td>
                        <button data-book-id="{{ book.id }}" id="submit" type="submit" value="Create Post">Create Post</button>
                    </td>
                </tr>
            </table>
        </form>
    </main>

    <script src="{% static 'js/create_post.js' %}"></script>
</body>

diskusiBook/templates/post.html
{% include 'header.html' %}

{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block meta %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock meta %}
    <title>Discussion Thread</title>
    <link rel="stylesheet" href="{% static 'css/post.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
</head>

<body>

    <main>
        <div class="jumbotron jumbotron-fluid" style="margin: 100px 30px 30px 30px;">
            <h1>Discussion thread for "{{ book.title }}"</h1>
        </div>

        <div class="row row-cols-1 g-4" id="comment-card"></div>
    </main>

    <script>
        var book_id = "{{ book.id }}";
        var post_id = "{{ post.pk }}";
        var get_comment_url = "{% url 'diskusiBook:get_comment_json' post.pk %}"
        var get_single_post_url = "{% url 'diskusiBook:get_single_post_json' post.pk %}"
        var user_id = "{{ user.id }}"
    </script>
    
    <script src="{% static 'js/post.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    

</body>

</html>

diskusiBook/templates/thread.html
{% include 'header.html' %}

{% load static %}

<!DOCTYPE html>
<html lang="en" id="html">

<head>
    {% block meta %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock meta %}
    <title>Discussion Thread</title>
    <link rel="stylesheet" href="{% static 'css/thread.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
</head>

<body>
    <main>
        <div class="jumbotron jumbotron-fluid" style="margin: 100px 30px 30px 30px;">
            <h1>Discussion thread for "{{ book.title }}"</h1>
        </div>

        <div class="row row-cols-1 g-4" id="post-card"></div>

        <!-- Button trigger modal -->
        <a href="{% url 'diskusiBook:create_post' book.id %}">
            <button type="button" class="btn btn-primary" id="createnewpost" style="margin: 30px 30px 30px 30px;">
                Create New Post
            </button>
        </a>
    </main>

    <script>
        var book_id = "{{ book.id }}";
        var get_post_url = "{% url 'diskusiBook:get_post_json' book.id %}"
        var user_id = "{{ user.id }}"
    </script>
    <script src="{% static 'js/thread.js' %}"></script>

</body>

</html>