ReadMe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('history/', include('history.urls')),
    path('list-book/', include('listBook.urls')),
    path('book-details/', include('bookDetails.urls')),
    path('diskusi-book/', include('diskusiBook.urls')),
    path('rating-book/', include('ratingBook.urls')),
    path('wishlist-book/', include('wishlistBook.urls')),
]

history/urls.py
from django.urls import path
from .views import history, show_history_json
from .views import add_search_history
from .views import history, add_search_history
from . import views

app_name = 'history'

urlpatterns = [
    path('', history, name='history'),
    path('add/', add_search_history, name='add-search-history'),
    path('delete/', views.delete_history_ajax, name='delete_history_ajax'),
    path('history-json/', show_history_json, name='show_history_json'), 
]

listBook/urls.py
from django.urls import path
from main.views import show_main
from listBook.views import add_book_flutter, delete_book_flutter, show_book_json, show_book_title_json, show_list, show_myBook, get_book, add_book, show_list_filter, delete_book, show_list_title, show_mybook_json

app_name = 'listBook'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('list-book', show_list, name='show_list'),
    path('list-book-filter/<str:genre>/', show_list_filter, name='show_list_filter'),
    path('show_list_title/', show_list_title, name='show_list_title'),
    path('my-book', show_myBook, name='show_myBook'),
    path('get-book/', get_book, name='get_book'),
    path('add-book/', add_book, name='add_book'),
    path('delete-book/<int:id>/', delete_book, name='delete_book'),
    path('myBook-json/', show_mybook_json, name='show_myBook_json'), 
    path('book-json/', show_book_json, name='show_book_json'), 
    path('book-json/<str:title>/', show_book_title_json, name='show_book_title_json'), 
    path('add-book-flutter/', add_book_flutter, name='add_book_flutter'),
    path('delete-book-flutter/<int:id>/', delete_book_flutter, name='delete_book_flutter'),
]

main/urls.py
from django.urls import path
from . import views # Tambah ini
from main.views import search_books, show_main, database_make, register, login_user, logout_user
from main.views import get_book, add_book

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('SECRET-ONLY/', database_make, name='database_make'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add_book/', add_book, name='add_book'),
    path('get-book/', get_book, name='get_book'),
    path('search-books/', search_books, name='search_books'),
]

ratingBook/urls.py
from django.urls import path
from ratingBook import views

app_name = 'ratingBook'

urlpatterns = [
    path('', views.show_rating, name='show_rating'),
    path('reviews/<int:id>/', views.get_rating_json, name='get_rating'),
    path('reviews/<int:id>/update/', views.show_rating_to_update, name='show_rating_to_update'),
    path('reviews/<int:id>/delete/', views.delete_rating, name='delete_rating'),
    path('reviews/create/', views.create_rating_ajax, name='create_rating'),
    path('reviews/update/', views.update_rating_ajax, name='update_rating'),
    path('rating-json/', views.show_rating_json, name='show_rating_json'), 
    path('mobile/create/', views.create_rating_flutter, name='create_rating_flutter'),
    path('mobile/update/', views.update_rating_flutter, name='update_rating_flutter'),
    path('mobile/delete/<int:id>/', views.delete_rating_flutter, name='delete_rating_flutter'),
    path('mobile/books/', views.get_book_json, name='get_book_json'),
    path('mobile/image/<int:id>/', views.get_book_image, name='get_book_image'),
    path('mobile/userid/', views.get_user_id, name='get_user_id'),
    path('mobile/israted/<int:id>/', views.get_is_rated, name='get_is_rated'),
]

wishlistBook/urls.py
from django.urls import path
from wishlistBook.views import show_wishlist, get_books_json, deleteWishlist, add_wishlist, get_json, add_flutter

app_name = 'wishlistBook'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('get-books-json/<int:book_id>/', get_books_json, name='get_books_json'),
    path('delete/', deleteWishlist, name='deleteWishlist'),
    path('add_wishlist/<int:book_id>/', add_wishlist, name='add_wishlist'),
    path('get-json/', get_json, name='get_json'),
    path('add-flutter/', add_flutter, name='add_fluter'),
]

ratingBook/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from main.models import Book

# Create your models here.
class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

ratingBook/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseForbidden, JsonResponse
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from .models import Rating, Book
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
import requests

# Create your views here.
@login_required(login_url='main:login')
def show_rating(request):
    books = Book.objects.all()

    context = {
        'books': books,
        'name': request.user.username,
    }

    return render(request, 'rating.html', context)

@login_required(login_url='main:login')
def show_rating_to_update(request, id):
    review = Rating.objects.get(id=id)
    book = Book.objects.get(id=review.book_id)

    if request.user != review.user:
        return HttpResponseForbidden('You are not allowed to update this rating')

    context = {
        'book': book,
        'review': review
    }

    return render(request, 'update.html', context)

def get_rating_json(request, id):
    ratings = Rating.objects.filter(book_id=id)

    data = []
    for rating in ratings:
        rating_dict = model_to_dict(rating)
        rating_dict['username'] = rating.user.username
        data.append(rating_dict)

    return JsonResponse(data, safe=False)

@login_required(login_url='main:login')
def create_rating_ajax(request):
    if request.method == 'POST':
        user = request.user
        book_id = request.POST['book']
        book = Book.objects.get(id=book_id)
        rating = request.POST['rating']
        message = request.POST['message']

        rating = Rating.objects.create(user=user, book=book, rating=rating, message=message)
        
        return HttpResponse('Rating created successfully', status=201)
    return HttpResponseForbidden('Allowed only via POST')

@login_required(login_url='main:login')
def update_rating_ajax(request):
    if request.method == 'POST':
        user = request.user
        book_id = request.POST['book']
        rating = request.POST['rating']
        message = request.POST['message']

        rating = Rating.objects.filter(user=user, book_id=book_id).update(rating=rating, message=message)
        
        return HttpResponse('Rating updated successfully', status=201)
    return HttpResponseForbidden('Allowed only via POST')

@login_required(login_url='main:login')
def delete_rating(request, id):
    rating = Rating.objects.get(id=id)
    if request.user == rating.user:
        rating.delete()
        return redirect('ratingBook:show_rating')
    return HttpResponseForbidden('You are not allowed to delete this rating')

def show_rating_json(request):
    data = Rating.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def create_rating_flutter(request):
    if request.method == 'POST':
        user = request.user
        book_id = request.POST['book']
        book = Book.objects.get(id=book_id)
        rating = request.POST['rating']
        message = request.POST['message']
        # check if user has rated this book
        if Rating.objects.filter(user=user, book_id=book_id).exists():
            return HttpResponseForbidden('You have rated this book')
        
        rating = Rating.objects.create(user=user, book=book, rating=rating, message=message)
        
        return HttpResponse('Rating created successfully', status=201)
    return HttpResponseForbidden('Allowed only via POST')

@csrf_exempt
def update_rating_flutter(request):
    if request.method == 'POST':
        user = request.user
        book_id = request.POST['book']
        rating = request.POST['rating']
        message = request.POST['message']

        rating = Rating.objects.filter(user=user, book_id=book_id).update(rating=rating, message=message)
        
        return HttpResponse('Rating updated successfully', status=201)
    return HttpResponseForbidden('Allowed only via POST')

@csrf_exempt
def delete_rating_flutter(request, id):
    rating = Rating.objects.get(id=id)
    if request.user == rating.user:
        rating.delete()
        return HttpResponse('Rating deleted successfully', status=201)
    return HttpResponseForbidden('You are not allowed to delete this rating')

def get_book_json(request):
    print(request.user)
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def get_book_image(request, id):
    book = Book.objects.get(id=id)
    # the image field is a url, so we need to get the image data
    image_data = requests.get(book.image).content
    return HttpResponse(image_data, content_type="image/png")

def get_user_id(request):
    if request.user.is_authenticated:
        return JsonResponse({'id': request.user.id}, status=200)
    return HttpResponseForbidden('You are not allowed to access this page')

def get_is_rated(request, id):
    if request.user.is_authenticated:
        if Rating.objects.filter(user=request.user, book_id=id).exists():
            return JsonResponse({'is_rated': True}, status=200)
        return JsonResponse({'is_rated': False}, status=200)
    return HttpResponseForbidden('You are not allowed to access this page')

ratingBook/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}ReadMe - The Future of Book Search{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/main_style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.7.1.slim.js" integrity="sha256-UgvvN8vBkgO0luPSUl2s8TIlOSYRoGFAX4jlCIm9Adc=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% block meta %}
    {% endblock meta %}
</head>

<body>
    {% include 'rating-header.html' %}

    {% block content %}
    {% endblock content %}
</body>

ratingBook/templates/book_rating.html
{% include 'header.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>404</h1>
            <p>Page not found</p>
        </div>
    </div>
</div>
{% endblock %}

ratingBook/templates/rating-header.html
<nav class="main-header">
    <a href="{% url 'main:show_main' %}" class="logo">
        <div >ReadMe</div>
    </a>
    <div class="main-nav">
        {% if user.is_authenticated %}
            <a href="{% url 'main:logout' %}" class="logout-btn">Logout</a>
            <a href="{% url 'listBook:show_list' %}">Book List</a>
            <a href="{% url 'wishlistBook:show_wishlist' %}">Saved</a>
            <a href="{% url 'history:history' %}">History</a>
        {% endif %}
        {% if not user.is_authenticated %}
            <a href="{% url 'listBook:show_list' %}">Book List</a>
            <a href="{% url 'main:login' %}">Saved</a>
            <a href="{% url 'main:login' %}">History</a>
            <a href="{% url 'main:register' %}" class="signup-btn">Sign up</a>
            <a href="{% url 'main:login' %}" class="login-btn" style="color: #0A74DA;">Login</a>
        {% endif %}
    </div>
    {% if user.is_authenticated %}
        <a href="#">
            <div id="profile">{{ name }}</div>
        </a>
    {% endif %}
</nav>

ratingBook/templates/rating.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ReadMe - Rating Book{% endblock title %}
{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>
{% endblock meta %}

{% block content %}
<div class="container">
    <section id="rating">
        <div class="container pt-5">
            <div class="row">
                <div class="text-center mx-auto">
                    <h2 class="display-6 fw-bold mb-4">Add your review!</h2>
                    <p class="text-muted">Your review will help other people to choose the right book. So, please, be honest and objective 😊 </p>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-6">
                    <div>
                        <form class="py-3 py-xl-4" method="POST">
                            {% csrf_token %}
                            <div class="mb-3">
                                <select class="shadow form-control selectpicker" required name="book" id="book" data-live-search="true" title="Choose a book">
                                    {% for book in books %}
                                    <option id="opt-{{book.id}}" data-tokens="{{ book.title }} {{ book.authors }}" value="{{ book.id }}">{{ book.title }} by {{ book.authors }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="mb-3">
                                <select class="shadow form-control selectpicker" required name="rating" id="rating" title="Choose a rating">
                                    <option value="1">⭐</option>
                                    <option value="2">⭐⭐</option>
                                    <option value="3">⭐⭐⭐</option>
                                    <option value="4">⭐⭐⭐⭐</option>
                                    <option value="5">⭐⭐⭐⭐⭐</option>
                                </select>
                            </div>
                            <div class="mb-3"><textarea id="message" class="shadow form-control" name="message" rows="6" required placeholder="Message"></textarea></div>
                            <div><button class="btn btn-primary shadow d-block w-100" type="submit" id="submit">Add Review</button></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="pb-5" id="reviews">
        <div class="container py-2 mt-2">
            <div class="row mb-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2 class="fw-bold">What people say about this book</h2>
                    <p class="text-muted">Read the reviews of people who have already read this book.</p>
                </div>
            </div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 d-sm-flex justify-content-sm-center" id="reviews-list">
            </div>
        </div>
    </section>
</div>

<script>
    // Variable to store the user id
    {% if user.is_authenticated %}
        let userId = {{ user.id }};
    {% else %}
        let userId = null;
    {% endif %}

    // Get the book id from the URL and set it as the default value of the book select
    const urlParams = new URLSearchParams(window.location.search);
    const bookId = urlParams.get('book');
    if (bookId) {
        document.getElementById('book').value = bookId;
        let title = document.getElementById(`opt-${bookId}`).innerHTML;
        // wait for the select to be initialized
        setTimeout(() => {
            // set the title of the book selector
            const bookSelector = document.querySelector("#rating > div > div.row.d-flex.justify-content-center > div > div > form > div:nth-child(2) > div > button")
            bookSelector.setAttribute("title", title);
            bookSelector.setAttribute("bs-placeholder", title);
            const bookSelectorTitle = document.querySelector("#rating > div > div.row.d-flex.justify-content-center > div > div > form > div:nth-child(2) > div > button > div > div > div")
            bookSelectorTitle.innerHTML = title;
        }, 100);
        refreshReviews();
    }

    // Get reviews by book id
    async function getReviews(id) {
        return fetch(`/rating-book/reviews/${id}`)
            .then(response => response.json());
    }

    // Refresh reviews list
    async function refreshReviews() {
        document.getElementById('reviews-list').innerHTML = '';
        document.getElementById('submit').disabled = false;
        document.getElementById('submit').innerHTML = 'Add Review';
        const reviews = await getReviews(document.getElementById('book').value);
        let html = '';
        reviews.forEach((review) => {
            html += `
            <div class="col mb-4">
                <div class="d-flex flex-column align-items-center align-items-sm-start">
                    <p class="bg-body-tertiary border rounded border-0 p-4">${review.message}</p>
                    <div class="d-flex">
                        <div>`
            if (review.user == userId) {
                html += `
                            <a href="/rating-book/reviews/${review.id}/update" class="btn btn-primary btn-sm">Update</a>
                            <a href="/rating-book/reviews/${review.id}/delete" class="btn btn-danger btn-sm">Delete</a>
                            `;
                document.getElementById('submit').disabled = true;
                document.getElementById('submit').innerHTML = 'You have already reviewed this book';
            };
            html += `
                            <p class="fw-bold text-primary mb-0">${review.username}</p>
                            <p class="text-muted mb-0">${'⭐'.repeat(review.rating)}</p>
                        </div>
                    </div>
                </div>
            </div>
            `;
        });
        document.getElementById('reviews-list').innerHTML = html;
    }

    // Add event listener to the book select
    document.getElementById('book').addEventListener('change', refreshReviews);

    // Add event listener to the form
    document.querySelector('form').addEventListener('submit', async (event) => {
        event.preventDefault();
        const response = fetch(`/rating-book/reviews/create/`, {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            },
            body: new FormData(event.target)
        }).then(() => {
            refreshReviews();
            document.getElementById('rating').value = '';
            document.getElementById('message').value = '';
        });
    });
</script>
{% endblock %}

ratingBook/templates/reviews.html
<div class="container">
    <div class="row mt-5">
        <div class="col-md-8 col-xl-6">
            <h2>Review</h2>
            {% if is_reviewed %}
            <a href="/rating-book/reviews/{{ user_review.id }}/update/" class="btn btn-primary btn-sm">Update Review</a>
            {% else %}
            <a href="/rating-book/?book={{ book.id }}" class="btn btn-primary btn-sm">Add Review</a>
            {% endif %}
        </div>
    </div>
    <div class="container py-2 mt-2">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 d-sm-flex justify-content-sm-center">
            {% for review in reviews %}
            <div class="col mb-4">
                <div class="d-flex flex-column align-items-center align-items-sm-start">
                    <p class="bg-body-tertiary border rounded border-0 p-4">{{ review.message }}</p>
                    <div class="d-flex">
                        <div>
                            <p class="fw-bold text-primary mb-0">{{ review.user }}</p>
                            <p class="text-muted mb-0">
                                {% if review.rating == 1 %}
                                ⭐
                                {% elif review.rating == 2 %}
                                ⭐⭐
                                {% elif review.rating == 3 %}
                                ⭐⭐⭐
                                {% elif review.rating == 4 %}
                                ⭐⭐⭐⭐
                                {% elif review.rating == 5 %}
                                ⭐⭐⭐⭐⭐
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

ratingBook/templates/update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ReadMe - Update Rating Book{% endblock title %}
{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>
{% endblock meta %}

{% block content %}
<section id="rating">
    <div class="container pt-5">
        <div class="row">
            <div class="text-center mx-auto">
                <h2 class="display-6 fw-bold mb-4">Update your review!</h2>
                <p class="text-muted">Your review will help other people to choose the right book. So, please, be honest and objective 😊 </p>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <div>
                    <form class="py-3 py-xl-4" method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <select class="shadow form-control selectpicker" required name="book" id="book" title="Choose a book">
                                <option data-tokens="{{ book.title }} {{ book.authors }}" value="{{ book.id }}" selected>{{ book.title }} by {{ book.authors }}</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <select class="shadow form-control selectpicker" required name="rating" id="rating" title="Choose a rating">
                                <option value="1" {% if review.rating == 1 %}selected{% endif %}>⭐</option>
                                <option value="2" {% if review.rating == 2 %}selected{% endif %}>⭐⭐</option>
                                <option value="3" {% if review.rating == 3 %}selected{% endif %}>⭐⭐⭐</option>
                                <option value="4" {% if review.rating == 4 %}selected{% endif %}>⭐⭐⭐⭐</option>
                                <option value="5" {% if review.rating == 5 %}selected{% endif %}>⭐⭐⭐⭐⭐</option>
                            </select>
                        </div>
                        <div class="mb-3"><textarea id="message" class="shadow form-control" name="message" rows="6" required placeholder="Message">{{ review.message }}</textarea></div>
                        <div><button class="btn btn-primary shadow d-block w-100" type="submit">Update Review</button></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    // Add event listener to the form
    document.querySelector('form').addEventListener('submit', (e) => {
        // Prevent the default behavior of the form
        e.preventDefault();
        const book = document.querySelector('#book').value;

        // Send the data to the server
        fetch('/rating-book/reviews/update/', {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',
            },
            body: new FormData(e.target)
        })
        .then(response => {
            // If message is updated, go to the reviews page
            if (response.status == 201) {
                window.location.href = `/rating-book/?book=${book}`;
            }
        });
    });
</script>
{% endblock content %}