ReadMe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('history/', include('history.urls')),
    path('list-book/', include('listBook.urls')),
    path('book-details/', include('bookDetails.urls')),
    path('diskusi-book/', include('diskusiBook.urls')),
    path('rating-book/', include('ratingBook.urls')),
    path('wishlist-book/', include('wishlistBook.urls')),
]

history/urls.py
from django.urls import path
from .views import history, show_history_json
from .views import add_search_history
from .views import history, add_search_history
from . import views

app_name = 'history'

urlpatterns = [
    path('', history, name='history'),
    path('add/', add_search_history, name='add-search-history'),
    path('delete/', views.delete_history_ajax, name='delete_history_ajax'),
    path('history-json/', show_history_json, name='show_history_json'), 
]

listBook/urls.py
from django.urls import path
from main.views import show_main
from listBook.views import add_book_flutter, delete_book_flutter, show_book_json, show_book_title_json, show_list, show_myBook, get_book, add_book, show_list_filter, delete_book, show_list_title, show_mybook_json

app_name = 'listBook'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('list-book', show_list, name='show_list'),
    path('list-book-filter/<str:genre>/', show_list_filter, name='show_list_filter'),
    path('show_list_title/', show_list_title, name='show_list_title'),
    path('my-book', show_myBook, name='show_myBook'),
    path('get-book/', get_book, name='get_book'),
    path('add-book/', add_book, name='add_book'),
    path('delete-book/<int:id>/', delete_book, name='delete_book'),
    path('myBook-json/', show_mybook_json, name='show_myBook_json'), 
    path('book-json/', show_book_json, name='show_book_json'), 
    path('book-json/<str:title>/', show_book_title_json, name='show_book_title_json'), 
    path('add-book-flutter/', add_book_flutter, name='add_book_flutter'),
    path('delete-book-flutter/<int:id>/', delete_book_flutter, name='delete_book_flutter'),
]

main/urls.py
from django.urls import path
from . import views # Tambah ini
from main.views import search_books, show_main, database_make, register, login_user, logout_user
from main.views import get_book, add_book

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('SECRET-ONLY/', database_make, name='database_make'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add_book/', add_book, name='add_book'),
    path('get-book/', get_book, name='get_book'),
    path('search-books/', search_books, name='search_books'),
]

wishlistBook/urls.py
from django.urls import path
from wishlistBook.views import show_wishlist, get_books_json, deleteWishlist, add_wishlist, get_json, add_flutter

app_name = 'wishlistBook'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('get-books-json/<int:book_id>/', get_books_json, name='get_books_json'),
    path('delete/', deleteWishlist, name='deleteWishlist'),
    path('add_wishlist/<int:book_id>/', add_wishlist, name='add_wishlist'),
    path('get-json/', get_json, name='get_json'),
    path('add-flutter/', add_flutter, name='add_fluter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=255)
    display_title = models.CharField(max_length=255)
    authors = models.TextField()
    image = models.TextField()
    description = models.TextField()
    isbn = models.CharField(max_length=255)
    genre = models.CharField(max_length=255)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

class MyMainBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    display_title = models.CharField(max_length=255)
    authors = models.TextField()
    image = models.TextField()
    description = models.TextField()
    isbn = models.CharField(max_length=255)

main/views.py
import json
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render
from .models import Book
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
import requests
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from .models import MyMainBook
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required


@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return redirect('main:show_main')

@csrf_exempt
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

@csrf_exempt
def show_main(request):
    context = {
        'name': request.user.username,
        'class': 'Test'
    }

    return render(request, "main.html", context)

BASE_URL = 'https://www.googleapis.com/books/v1/volumes'
API_KEY = "AIzaSyByhU8BReRCv4y_APglq06WoUX0GCEPvns" 

def fetch_books(query, max_results=40):
    """
    Ambil buku dari Google Books API berdasarkan query.
    """
    params = {
        'q': query,
        'key': API_KEY,
        'maxResults': max_results
    }

    response = requests.get(BASE_URL, params=params)
    response.raise_for_status()

    results = response.json()
    books = results.get('items', [])
    return books

def max_title(title, max_length=20):  # mengganti parameter max_words dengan max_length
    if len(title) > max_length:
        return title[:max_length-3] + '...'  # mengurangkan 3 karena kita menambahkan '...'
    return title


def database_make(request):
    Book.objects.all().delete()
    query = [
        "romance comedy",
        "action",
        "Fantasy",
        "fiction",
        "manga",
        "science",
    ]
    for i in range(len(query)):
        books_data = fetch_books(query[i], 20)

        # Potong setiap judul buku
        for book_data in books_data:
            title = book_data['volumeInfo']['title']
            authors = ", ".join(book_data['volumeInfo'].get('authors', []))
            image = book_data['volumeInfo']['imageLinks']['thumbnail']
            description = book_data['volumeInfo'].get('description', 'No description available')
            industryIdentifiers = book_data['volumeInfo'].get('industryIdentifiers', [])
            isbn = ""
            genre = query[i]
            
            for identifier in industryIdentifiers:
                if identifier['type'] == 'ISBN_13':
                    isbn = identifier['identifier']
                    break

            book = Book(
                title=title,
                display_title=max_title(title),
                authors=authors,
                image=image,
                description=description,
                isbn=isbn,
                genre=genre                 
            )
            book.save()
    return HttpResponse(b"CREATED DATABASE", status=201)

def get_book(request):
    books = MyMainBook.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', books))

@csrf_exempt
def add_book(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        display_title = max_title(title)
        authors = request.POST  .get("authors")
        image = request.POST.get("image")
        description = request.POST.get("description")
        isbn = request.POST.get("isbn")
        user = request.user

        new_book = MyMainBook(
            title=title, 
            display_title=display_title, 
            authors=authors, 
            image=image, 
            description=description,
            isbn=isbn,
            user=user,
        )
        new_book.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()


def show_book_json(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def search_books(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            query = data.get('query')

            # Debug: Cetak query untuk memastikan isi query
            print(f"Query: {query}")

            response = requests.post(
                'https://octopus-app-cvv6j.ondigitalocean.app/AI_Search',
                headers={'Content-Type': 'application/json'},
                json={'context': query}
            )

            # Debug: Cetak status code dan response untuk memeriksa hasil
            print(f"Status Code: {response.status_code}")
            print(f"Response: {response.json()}")

            if response.status_code == 200:
                books_data = response.json()
                return JsonResponse({'books': books_data.get('books', [])})
            else:
                return JsonResponse({'error': 'Error with external book API'}, status=response.status_code)

        except Exception as e:
            print(f"Exception: {e}")  # Debug: Cetak exception jika terjadi
            return JsonResponse({'error': str(e)}, status=500)
        
    return HttpResponseNotFound()

main/templates/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ReadMe - The Future of Book Search</title>
    <link rel="stylesheet" href="{% static 'css/main_style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <nav class="main-header">
        <a href="{% url 'main:show_main' %}" class="logo">
            <div >ReadMe</div>
        </a>
        <div class="main-nav">
            {% if user.is_authenticated %}
                <a href="{% url 'main:logout' %}" class="logout-btn">Logout</a>
                <a href="{% url 'listBook:show_list' %}">Book List</a>
                <a href="{% url 'wishlistBook:show_wishlist' %}">Saved</a>
                <a href="{% url 'history:history' %}">History</a>
            {% endif %}
            {% if not user.is_authenticated %}
                <a href="{% url 'listBook:show_list' %}">Book List</a>
                <a href="{% url 'main:login' %}">Saved</a>
                <a href="{% url 'main:login' %}">History</a>
                <a href="{% url 'main:register' %}" class="signup-btn">Sign up</a>
                <a href="{% url 'main:login' %}" class="login-btn" style="color: #0A74DA;">Login</a>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
            <a href="#">
                <div id="profile">{{ name }}</div>
            </a>
        {% endif %}
    </nav>
    {% block meta %}
    {% endblock meta %}
</head>

<body>
    {% block content %}
    {% endblock content %}
</body>

main/templates/list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ReadMe - The Future of Book Search</title>
        <link rel="stylesheet" href="{% static 'css/list_book_style.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

        <header class="main-header">
            <div class="logo">
                <a href="#"></a>
                ReadMe
            </div>
            <nav class="main-nav">
                <a href="#">Sorting Book</a>
            </nav>
        </header>
    </head>
    <body>
        <section>
            <div class="container-fluid">
                <div id="card-container">
                    {% for book in books %}
                    <div class="card text-center">
                            <img src="{{ book.image }}" alt="{{ book.title }} Cover"> 
                            <div class="book-title">
                                <h2>{{ book.display_title }}</h2>
                            </div>
                            <p>Penulis: {{ book.authors }}</p>
                            <button id="rating-btn">Details</button>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>

        
        <div id="bookList">
            
        </div>
        
    </body>    
</html>

main/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ReadMe - The Future of Book Search</title>
        <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.2/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.2/components/logins/login-9/assets/css/login-9.css" />
        <style>
            .logo {
                font-size: 48px; /* Atur ukuran font */
                font-weight: bold; /* Jadikan teks tebal */
                color: #ffffff; /* Atur warna teks */
            }
        </style>
    </head>
</html>

  <section class="bg-primary py-3 py-md-5 py-xl-8">
    <div class="container">
      <div class="row gy-4 align-items-center">
        <div class="col-12 col-md-6 col-xl-5">
          <div class="card border-0 rounded-4">
            <div class="card-body p-3 p-md-4 p-xl-5">
              <div class="row">
                <div class="col-12">
                  <div class="mb-4">
                    <h3>Login</h3>
                    <p>Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
                  </div>
                </div>
              </div>
              <form method="POST" action="">
                {% csrf_token %}
                <div class="row gy-3 overflow-hidden">
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      <input type="text" class="form-control" name="username" id="username" placeholder="Username" required>
                      <label for="username" class="form-label">Username</label>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      <input type="password" class="form-control" name="password" id="password" placeholder="Password" required>
                      <label for="password" class="form-label">Password</label>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="d-grid">
                      <input class="btn btn-primary btn-lg" type="submit" value="Login">
                    </div>
                  </div>
                </div>
              </form>
              <div class="row">
                <div class="col-12">
                  <div class="d-flex gap-2 gap-md-4 flex-column flex-md-row justify-content-md-end mt-4">
                    <a href="#!">Forgot password</a>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <p class="mt-4 mb-4">Or continue with</p>
                  <div class="d-flex gap-2 gap-sm-3 justify-content-centerX">
                    <a href="#!" class="btn btn-outline-danger bsb-btn-circle bsb-btn-circle-2xl">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-google" viewBox="0 0 16 16">
                        <path d="M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z" />
                      </svg>
                    </a>
                    <a href="#!" class="btn btn-outline-primary bsb-btn-circle bsb-btn-circle-2xl">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
                      </svg>
                    </a>
                    <a href="#!" class="btn btn-outline-dark bsb-btn-circle bsb-btn-circle-2xl">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-apple" viewBox="0 0 16 16">
                        <path d="M11.182.008C11.148-.03 9.923.023 8.857 1.18c-1.066 1.156-.902 2.482-.878 2.516.024.034 1.52.087 2.475-1.258.955-1.345.762-2.391.728-2.43Zm3.314 11.733c-.048-.096-2.325-1.234-2.113-3.422.212-2.189 1.675-2.789 1.698-2.854.023-.065-.597-.79-1.254-1.157a3.692 3.692 0 0 0-1.563-.434c-.108-.003-.483-.095-1.254.116-.508.139-1.653.589-1.968.607-.316.018-1.256-.522-2.267-.665-.647-.125-1.333.131-1.824.328-.49.196-1.422.754-2.074 2.237-.652 1.482-.311 3.83-.067 4.56.244.729.625 1.924 1.273 2.796.576.984 1.34 1.667 1.659 1.899.319.232 1.219.386 1.843.067.502-.308 1.408-.485 1.766-.472.357.013 1.061.154 1.782.539.571.197 1.111.115 1.652-.105.541-.221 1.324-1.059 2.238-2.758.347-.79.505-1.217.473-1.282Z" />
                        <path d="M11.182.008C11.148-.03 9.923.023 8.857 1.18c-1.066 1.156-.902 2.482-.878 2.516.024.034 1.52.087 2.475-1.258.955-1.345.762-2.391.728-2.43Zm3.314 11.733c-.048-.096-2.325-1.234-2.113-3.422.212-2.189 1.675-2.789 1.698-2.854.023-.065-.597-.79-1.254-1.157a3.692 3.692 0 0 0-1.563-.434c-.108-.003-.483-.095-1.254.116-.508.139-1.653.589-1.968.607-.316.018-1.256-.522-2.267-.665-.647-.125-1.333.131-1.824.328-.49.196-1.422.754-2.074 2.237-.652 1.482-.311 3.83-.067 4.56.244.729.625 1.924 1.273 2.796.576.984 1.34 1.667 1.659 1.899.319.232 1.219.386 1.843.067.502-.308 1.408-.485 1.766-.472.357.013 1.061.154 1.782.539.571.197 1.111.115 1.652-.105.541-.221 1.324-1.059 2.238-2.758.347-.79.505-1.217.473-1.282Z" />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6 col-xl-7">
            <div class="d-flex justify-content-center text-bg-primary">
                <div class="col-12 col-xl-9">
                    <h1 class="logo">ReadMe.</h1>
                    <hr class="border-primary-subtle mb-4">
                    <h2 class="h1 mb-4">AI-Powered Book Discovery.</h2>
                    <p class="lead mb-5">We make people smarter with artificial intelligence.</p>
                    <div class="text-endx">
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </section>
  


<!-- <div class = "login">
    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>

</div> -->

main/templates/main.html
{% include 'header.html' %}

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body id="search-container">
    <div class="background-animation"></div>
    <div class="container">
        <h1 class="tagline">AI-Powered Book Discovery.</h1>
        <div class="search-bar">
            <input type="text" placeholder="Contoh: saya anak smp, saya perlu buku mtk" id="searchInput">
            <button id="searchBtn">Search</button>
            <div class="loading" id="loadingIndicator">
                <div class="spinner"></div>
            </div>
        </div>
        <button class="button-jns button-add" data-bs-toggle="modal" data-bs-target="#exampleModal">Add to my books</button>

        <div id="searchResults" class="search-results"></div>
    </div>
    


    <div id="bookModal" class="book-modal" style="display: none;">
        <div class="book-list">
            <!-- The book details will be appended here using JS -->
        </div>
        <button class="close-modal" onclick="closeModal()">Close</button>
      </div>

    

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Book</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="title" class="col-form-label">Title:</label>
                            <input type="text" class="form-control" id="title" name="title"></input>
                        </div>
                        <div class="mb-3">
                            <label for="authors" class="col-form-label">Authors:</label>
                            <input type="text" class="form-control" id="authors" name="authors"></input>
                        </div>
                        <div class="mb-3">
                            <label for="isbn" class="col-form-label">ISBN:</label>
                            <input type="text" class="form-control" id="isbn" name="isbn"></input>
                        </div>
                        <div class="mb-3">
                            <label for="image" class="col-form-label">Image:</label>
                            <textarea class="form-control" id="image" name="image"></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/main_script.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/list_script.js' %}"
        data-get-book-url="{% url 'main:get_book' %}"
        data-add-book-url="{% url 'main:add_book' %}">
    </script>
    <script>
    let placeholders = ["saya lagi sedih, kasih saya rekomendasi buku", "saya anak SMA, saya mau belajar ngoding python", "aku mau buku tentang spy dan misteri!"];
    let count = 0;
    let index = 0;
    let currentText = '';
    let letter = '';
    let isDeleting = false;

    (function type(){    
        if(count === placeholders.length){
            count = 0;
        }
        currentText = placeholders[count];
        if (!isDeleting) {
            letter = currentText.slice(0, ++index);
            if(letter.length === currentText.length){
                isDeleting = true;
                setTimeout(type, 1000); //delay sebelum delete
            } else {
                setTimeout(type, 50); //speed typing                         
            }
        } else {
            letter = currentText.slice(0, --index);
            if(letter.length === 0) {
                isDeleting = false;
                count++;
            }
            setTimeout(type, 50); //speed delete
        }
        document.querySelector('#searchInput').placeholder = letter;
    }());

    document.getElementById("searchBtn").addEventListener("click", function(e) {
        e.preventDefault();
        let query = document.getElementById("searchInput").value;
        if(query) {
            document.getElementById("searchBtn").disabled = true;
            document.getElementById("searchBtn").classList.add("disabled");
            document.getElementById("loadingIndicator").style.display = "block";
            searchBooks(query).then(() => {
                document.getElementById("searchBtn").disabled = false;
                document.getElementById("searchBtn").classList.remove("disabled");
                document.getElementById("loadingIndicator").style.display = "none";
            }).catch((error) => {
                console.error('Error:', error);
                document.getElementById("searchBtn").disabled = false;
                document.getElementById("searchBtn").classList.remove("disabled");
                document.getElementById("loadingIndicator").style.display = "none";
            });
        }
    });
    </script>
</body>
</html>