ReadMe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('history/', include('history.urls')),
    path('list-book/', include('listBook.urls')),
    path('book-details/', include('bookDetails.urls')),
    path('diskusi-book/', include('diskusiBook.urls')),
    path('rating-book/', include('ratingBook.urls')),
    path('wishlist-book/', include('wishlistBook.urls')),
]

bookDetails/urls.py
from django.urls import path
from main.views import show_main
from bookDetails.views import show_details, show_details_myBook

app_name = 'bookDetails'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('details-book/allBook/<int:id>/', show_details, name='show_details'),
    path('details-book/myBook/<int:id>/', show_details_myBook, name='show_details_myBook'),
]

listBook/urls.py
from django.urls import path
from main.views import show_main
from listBook.views import add_book_flutter, delete_book_flutter, show_book_json, show_book_title_json, show_list, show_myBook, get_book, add_book, show_list_filter, delete_book, show_list_title, show_mybook_json

app_name = 'listBook'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('list-book', show_list, name='show_list'),
    path('list-book-filter/<str:genre>/', show_list_filter, name='show_list_filter'),
    path('show_list_title/', show_list_title, name='show_list_title'),
    path('my-book', show_myBook, name='show_myBook'),
    path('get-book/', get_book, name='get_book'),
    path('add-book/', add_book, name='add_book'),
    path('delete-book/<int:id>/', delete_book, name='delete_book'),
    path('myBook-json/', show_mybook_json, name='show_myBook_json'), 
    path('book-json/', show_book_json, name='show_book_json'), 
    path('book-json/<str:title>/', show_book_title_json, name='show_book_title_json'), 
    path('add-book-flutter/', add_book_flutter, name='add_book_flutter'),
    path('delete-book-flutter/<int:id>/', delete_book_flutter, name='delete_book_flutter'),
]

main/urls.py
from django.urls import path
from . import views # Tambah ini
from main.views import search_books, show_main, database_make, register, login_user, logout_user
from main.views import get_book, add_book

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('SECRET-ONLY/', database_make, name='database_make'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add_book/', add_book, name='add_book'),
    path('get-book/', get_book, name='get_book'),
    path('search-books/', search_books, name='search_books'),
]

listBook/models.py
from django.db import models
from main.models import Book
from django.contrib.auth.models import User

# Create your models here.
class myBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    display_title = models.CharField(max_length=255)
    authors = models.TextField()
    image = models.TextField()
    description = models.TextField()
    isbn = models.CharField(max_length=255)

listBook/forms.py
from django.forms import ModelForm
from listBook.models import myBook

class ProductForm(ModelForm):
    class Meta:
        model = myBook
        fields = ["title", "image", "authors"]

listBook/views.py
import json
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers
from django.shortcuts import redirect, render
from main.models import Book, MyMainBook
from listBook.models import myBook
from django.views.decorators.csrf import csrf_exempt
from main.views import max_title
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/login')
def show_list(request):
    books = Book.objects.all()

    context = {
        'name': request.user.username,
        'books': books,
    }
    return render(request, "list.html", context)

@login_required(login_url='/login')
def show_list_filter(request, genre):
    temp_books = Book.objects.all()
    books = []

    for i in temp_books:
        if genre in i.genre:
           books.append(i)

    context = {
        'name': request.user.username,
        'books': books,
    }
    return render(request, "list.html", context)

@login_required(login_url='/login')
def show_list_title(request):
    title_query = request.GET.get('title', '')
    temp_books = Book.objects.filter(title__icontains=title_query) 

    context = {
        'name': request.user.username,
        'books': temp_books,
    }
    return render(request, "list.html", context)

@login_required(login_url='/login')
def show_myBook(request):
    books = myBook.objects.filter(user=request.user)
    booksFromMain = MyMainBook.objects.filter(user=request.user)

    tempBooks = []

    tempBooks.extend(books)
    tempBooks.extend(booksFromMain)

    context = {
        'name': request.user.username,
        'books': tempBooks,
    }
    return render(request, "myBook.html", context)

@csrf_exempt
def get_book(request):
    books = myBook.objects.filter(user=request.user)

    booksFromMain = MyMainBook.objects.filter(user=request.user)

    tempBooks = []

    tempBooks.extend(books)
    tempBooks.extend(booksFromMain)

    return HttpResponse(serializers.serialize('json', tempBooks))

@csrf_exempt
def add_book(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        display_title = max_title(title)
        authors = request.POST.get("authors")
        image = request.POST.get("image")
        description = request.POST.get("description")
        isbn = request.POST.get("isbn")
        user = request.user

        new_book = myBook(
            title=title, 
            display_title=display_title, 
            authors=authors, 
            image=image,  
            description=description,
            isbn=isbn,
            user=user,
        )
        new_book.save() 

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_book(request, id):
    book = myBook.objects.get(user = request.user, pk = id)
    book.delete()

    return redirect('listBook:show_myBook')

@csrf_exempt
def delete_book_flutter(request, id):
    if request.method == 'POST':
        try:
            book = myBook.objects.get(pk=id, user=request.user)
            book.delete()
            return JsonResponse({"status": "success"}, status=200)
        except myBook.DoesNotExist:
            return JsonResponse({"status": "error", "message": "Book not found"}, status=404)

    return JsonResponse({"status": "error", "message": "Invalid request"}, status=400)

@csrf_exempt
def show_mybook_json(request):
    data = myBook.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def add_book_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        title = data["title"]
        display_title = max_title(title)
        authors = data["authors"]
        image = data["image"]
        description = data["description"]
        isbn = data["isbn"]
        user = request.user

        new_product = myBook.objects.create(
            title=title, 
            display_title=display_title, 
            authors=authors, 
            image=image, 
            description=description,
            isbn=isbn,
            user=user,
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt   
def show_book_json(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def show_book_title_json(request, title):
    data = Book.objects.filter(title__icontains=title)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

listBook/templates/list.html
{% include 'header.html' %}

{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/list_book_style.css' %}">
</head>
<body>
    <section>
        <div class="container-fluid">
            <div class="button-group">
                <div class="center-buttons">
                    <a href="{% url 'listBook:show_list' %}" class="button-jns button-active">
                        All Book
                    </a>
                    <a href="{% url 'listBook:show_myBook' %}" class="button-jns">
                        My Book
                    </a>
                </div>
            </div>
            <div class="button-filter-cont">
                <div class="center-buttons">
                    <form method="get" action="{% url 'listBook:show_list_title' %}" id="filterForm" class="mb-3">
                        <div class="input-group">
                            <input type="text" class="form-control" name="title" placeholder="Search by Title">
                            <div class="dropdown">
                                <button type="submit" class="btn btn-primary">Filter</button>
                                <div class="dropdown-content">
                                    <a href="{% url 'listBook:show_list' %}">All</a>
                                    <a href="{% url 'listBook:show_list_filter' genre='action' %}">Action</a>
                                    <a href="{% url 'listBook:show_list_filter' genre='romance' %}">Romance</a>
                                    <a href="{% url 'listBook:show_list_filter' genre='science' %}">Science</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div id="card-container">
                {% for book in books %}
                    <div class="card text-center">
                        <div style="position: relative; z-index: 2;">
                            <a href="{% url 'bookDetails:show_details' id=book.id %}" style="display: block; position: relative; z-index: 1;">
                                <img src="{{ book.image }}" alt="{{ book.title }} Cover" style="z-index: 0;"> 
                            </a>
                        </div>
                        <div class="book-title">
                            <h2>{{ book.display_title }}</h2>
                        </div>
                        <p>Penulis: {{ book.authors }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

</body>    

listBook/templates/myBook.html
{% include 'header.html' %}

{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/list_book_style.css' %}">
</head>

<body>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Book</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="title" class="col-form-label">Title:</label>
                            <input type="text" class="form-control" id="title" name="title"></input>
                        </div>
                        <div class="mb-3">
                            <label for="authors" class="col-form-label">Authors:</label>
                            <input type="text" class="form-control" id="authors" name="authors"></input>
                        </div>
                        <div class="mb-3">
                            <label for="isbn" class="col-form-label">ISBN:</label>
                            <input type="text" class="form-control" id="isbn" name="isbn"></input>
                        </div>
                        <div class="mb-3">
                            <label for="image" class="col-form-label">Image:</label>
                            <textarea class="form-control" id="image" name="image"></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                </div>
            </div>
        </div>
    </div>

    <section>
        <div class="container-fluid">
            <div class="button-group">
                <div class="center-buttons">
                    <a href="{% url 'listBook:show_list' %}" class="button-jns">
                        All Book
                    </a>
                    <a href="{% url 'listBook:show_myBook' %}" class="button-jns button-active">
                        My Book
                    </a>
                </div>
            </div>
            <div class="button-filter-cont">
                <div class="center-buttons">
                    <a href="#" class="button-jns button-add" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Tambah Buku
                    </a>
                </div>
            </div>
            <div id="card-container2" class="save-card">
                <!-- Menampilkan card books -->
            </div>
        </div>
    </section>

    <script src="{% static 'js/list_script.js' %}"
            data-get-book-url="{% url 'listBook:get_book' %}"
            data-add-book-url="{% url 'listBook:add_book' %}">
    </script>
</body>